version: "3.7"
services:
  back:
    build:
      args:
        user: laravel
        uid: 1000
      context: ""
      dockerfile: Dockerfile
    image: laravel
    container_name: back
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    env_file: .env

  db:
    image: postgres:14.3-bullseye
    restart: always
    container_name: pg
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file: .env

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
